### ISSUE TITLE
No summary file

### ISSUE THREAD

**Issue by liamfriar** [Arkadiy-Garber/SprayNPray#9]
Hi,

I am using the following call to spray-and-pray.py:
`
spray-and-pray.py -t 20 --euk --meta --spades -bam ${prefix}.pairedReads2assembly.sorted.bam -g $file -ref /home/liam/data/nr/nr.dmnd -out spraynpray_out/$bin`

I am receiving the following error. The number "1.00425e+06" is the same across all of my datasets, so I assume that is internal to spray and pray, and not a function of my data? 

```
Running Prodigal: calling ORFs from provided contigs

Running Diamond BLAST

Extracting coverage information from the provided BAM files

Calculating GC-content

Preparing summary: spraynpray_out/rubra.4.csv

Traceback (most recent call last):
  File "/home/liam/tools/SprayNPray/spray-and-pray.py", line 779, in <module>
    depthDict[ls[0]]["length"] = int(ls[1])
ValueError: invalid literal for int() with base 10: '1.00425e+06'
```

This is inside a for loop that is printing $bin, $prefix, and $file each iteration, so I am sure those are assigned correctly.

The files that are being generated are:
*-cds.ffn (which has the variable $file as its prefix instead of what follows the -out flag)
*-proteins.faa (which has the variable $file as its prefix instead of what follows the -out flag)
*.blast (which has the variable $file as its prefix instead of what follows the -out flag)
*-top100.csv
I think there is supposed to be at least one other file? Which I assume is the "preparing summary" output that is being blocked by that error?

**Comment by liamfriar** [comment]
Sorry that that error is printed without the proper new lines...I tried unsuccessfully to edit that post to fix that.

**Comment by Arkadiy-Garber** [comment]
No worries, you just need to leave extra spaces between lines indicated as code.

For the error, I found the bug and addressed it. Could you try re-downloading the github repo and trying again with the updated code. Let me know if you continue to have issues!

Cheers,
Arkadiy

**Comment by liamfriar** [comment]
I now get the following:
##It printed a bunch to sdout with 2-line units that lookedl like:

```
NODE_1206_length_2518_cov_2.828258_7 # 2167 # 2508 # 1 # ID=290_7;partial=00;start_type=GTG;rbs_motif=None;rbs_spacer=None;gc_cont=0.567

MKQPLVDVVRRLIQKIVVGPRPGHQQASLEIHGQIASILAAMEAATIMEKQLITLHHHQYLEAEDAGLLDTEDKRKKLLSDFAEELEVRRQQWRNLQVSVVAGAGFEPAAFRL*
```
##Then:

```
Running Diamond BLAST

Calculating GC-content

Preparing summary: spraynpray_out_wDepthOpt/rubra.unbinned.csv

Traceback (most recent call last):

  File "/home/liam/tools/SprayNPray/spray-and-pray.py", line 1000, in <module>

    summary = open("%s/%s.csv" % (outdir, outfilename)) 

FileNotFoundError: [Errno 2] No such file or directory: 

'spraynpray_out_wDepthOpt/rubra.unbinned/spraynpray_out_wDepthOpt/rubra.unbinned.csv'
```
It looks like the out prefix got cat'ed to itself?
